spring:
  #SQL config
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  session:
    jdbc:
      initialize-schema: always

  # Application
  application:
    name: Nova
#jwt:
##  secret: your_super_secret_key_which_is_long_enough_256_bits
#  access-expiration: 900000        # 15 ?????
#  refresh-expiration: 604800000    # 7 ????